name: CI
on:
    pull_request:
    push:
jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest
        steps:
            - uses: actions/checkout@v3.5.2
            - uses: actions/setup-node@v3.6.0
              with:
                  node-version: "20.x"
            - uses: actions/cache@v3.3.1
              with:
                  path: ~/.local/share/pnpm/store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-
            - run: |
                  corepack enable
                  corepack prepare pnpm@8.6.3 --activate
                  pnpm config set store-dir ~/.local/share/pnpm/store
                  pnpm install
              env:
                  PNPM_HOME: /home/runner/.local/bin
            - run: make test
